experimental_monorepo_root = true

[tools]
hk = "1.32.0"
pkl = "0.30.2"

[env]
MISE_EXPERIMENTAL = "1"
HK_MISE = "1"

[tasks.pre-commit]
run = "hk run pre-commit"
description = "Run pre-commit hooks"
